### ISSUE TITLE
Why does the trained model need clean audio files for inferencing on the same noisy audio files?

### ISSUE THREAD

**Issue by DillipKS** [drethage/speech-denoising-wavenet#10]
Ideally, while inferencing the trained model should take the noisy audio data and output the denoised/cleaned version of the same audio files. I have some noisy audio files on which I want to run the pretrained model and get the clean files. But, while inferencing, it asks for path to clean audio data too which I don't have and the model doesn't run without it. 
Why is a previously trained model asking for clean audio files? @drethage

**Comment by jordipons** [comment]
If you remove the "--clean_input_path data/NSDTSEA/clean_testset_wav" part of your script call, it should work.

**Comment by DillipKS** [comment]
Thanks for the info @jordipons . Can you also clarify if the training/test data needs to be in .wav format or it can support any other format? I have audio data in .mp3 format and converting it to .wav is resource intensive. How can I train and test the wavenet model with data in mp3 format itself?

**Comment by drethage** [comment]
During inference, the clean audio files are only used for computing statistics on the output.
