### ISSUE TITLE
Method to evaluate enhanced speech

### ISSUE THREAD

**Issue by lifelongeek** [drethage/speech-denoising-wavenet#3]
Could you provide some additional information or evaluation script for enhanced speech? (to getting SIG, BAK, OVL)

**Comment by drethage** [comment]
Hi gmkim90, implementations of the objective measures (SIG, BAK, OVL) used for evaluation can be found at: https://www.crcpress.com/downloads/K14513/K14513_CD_Files.zip in MATLAB_code/objective_measures/quality.

**Comment by lifelongeek** [comment]
Thank you for the information :+1:
