### ISSUE TITLE
got wrong array shape

### ISSUE THREAD

**Issue by tonyyyye** [drethage/speech-denoising-wavenet#6]
we have trained using our test data, but there are errors reported as 

> ValueError: Error when checking : expected condition_input to have shape (None, 1) but got array with shape (1, 5)

I wonder what the errors may be like, how we can fix it, and how are the designated target wav can be created. Noted that we have only clean wav files with 16000 sample rate.

Thanks

**Comment by tonyyyye** [comment]
i think i have fixed that by ffmpeg to resample it in the same format, but still i am not sure if this data preparation method is suitable for training. At least my training result is not as good as the demo one. Hope you can help me about that.
Thank you.

**Comment by tonyyyye** [comment]
we have also encountered another problem showing that the result  is blank with SNR 0.00000dB.

**Comment by drethage** [comment]
Hi tonyyye,

the ValueError is thrown because the model expects a scalar condition per training sample, you are trying to supply it with a 1x5 vector.

You don't need to preprocess the training data. The wav loading function will downsample audio to 16kHz automatically.
